# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('userPassword', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastLoginTime', models.DateField(auto_now=True)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
